// Types Product
// ### Get Products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_PENDING = 'GET_PRODUCTS_PENDING';
export const GET_PRODUCTS_REJECTED = 'GET_PRODUCTS_REJECTED';
export const GET_PRODUCTS_FULFILLED = 'GET_PRODUCTS_FULFILLED';
// ### Get Product
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_PENDING = 'GET_PRODUCT_PENDING';
export const GET_PRODUCT_REJECTED = 'GET_PRODUCT_REJECTED';
export const GET_PRODUCT_FULFILLED = 'GET_PRODUCT_FULFILLED';
// ### Create Product
export const CREATE_PRODUCT_PENDING = 'CREATE_PRODUCT_PENDING';
export const CREATE_PRODUCT_REJECTED = 'CREATE_PRODUCT_REJECTED';
export const CREATE_PRODUCT_FULFILLED = 'CREATE_PRODUCT_FULFILLED';
// ### Delete Product
export const DELETE_PRODUCT_PENDING = 'DELETE_PRODUCT_PENDING';
export const DELETE_PRODUCT_REJECTED = 'DELETE_PRODUCT_REJECTED';
export const DELETE_PRODUCT_FULFILLED = 'DELETE_PRODUCT_FULFILLED';
// ### Update Product
export const UPDATE_PRODUCT_PENDING = 'UPDATE_PRODUCT_PENDING';
export const UPDATE_PRODUCT_REJECTED = 'UPDATE_PRODUCT_REJECTED';
export const UPDATE_PRODUCT_FULFILLED = 'UPDATE_PRODUCT_FULFILLED';

// Types Order
// ### Get Orders
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_PENDING = 'GET_ORDERS_PENDING';
export const GET_ORDERS_REJECTED = 'GET_ORDERS_REJECTED';
export const GET_ORDERS_FULFILLED = 'GET_ORDERS_FULFILLED';
// ### Get Order
export const GET_ORDER_PENDING = 'GET_ORDER_PENDING';
export const GET_ORDER_REJECTED = 'GET_ORDER_REJECTED';
export const GET_ORDER_FULFILLED = 'GET_ORDER_FULFILLED';
// ### Create Order
export const CREATE_ORDER_PENDING = 'CREATE_ORDER_PENDING';
export const CREATE_ORDER_REJECTED = 'CREATE_ORDER_REJECTED';
export const CREATE_ORDER_FULFILLED = 'CREATE_ORDER_FULFILLED';
// ### Delete Order
export const DELETE_ORDER_PENDING = 'DELETE_ORDER_PENDING';
export const DELETE_ORDER_REJECTED = 'DELETE_ORDER_REJECTED';
export const DELETE_ORDER_FULFILLED = 'DELETE_ORDER_FULFILLED';
// ### Update Order
export const UPDATE_ORDER_PENDING = 'UPDATE_ORDER_PENDING';
export const UPDATE_ORDER_REJECTED = 'UPDATE_ORDER_REJECTED';
export const UPDATE_ORDER_FULFILLED = 'UPDATE_ORDER_FULFILLED';
